[package]
name = "awc"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "awc"

[dependencies]
apollo-compiler = "0.3"
buildstructor = "0.5"
miette = "4"
tracing = "0.1"
saucer = { path = "../saucer" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"